### ISSUE TITLE
[Command] Add optional parameters to `GetBlocksInChain` command

### ISSUE THREAD

**Issue by liam0215** [tz-rs/tz-rs#6]
Optional parameters as described [here](https://gitlab.com/tezos/tezos/-/blob/master/docs/api/rpc-openapi.json): 
![image](https://user-images.githubusercontent.com/8989334/117243093-84708180-ae04-11eb-82fe-7176d80f7fb5.png)

Endpoint is `/chains/<chain_id>/blocks?[length=<int>]&(head=<block_hash>)*&[min_date=<date>]`

**Comment by astherath** [comment]
Since the current implementation of `JsonArray` only allows for flat arrays, we flatten by default, turning something like 
`[["..."], ["..."], ...]`
into
`["...", "...", ...]`.

This feels like taking a decision _for_ the SDK user, and might make them write double the code for the arrays that we can flatten vs. the ones that we can't.

My current proposal is to make `JsonArray<T>` **always** represent a nested `Vec<Vec<T>>` so the struct holding the data represents the data being handed to us by the RPC call faithfully. 

We could, for convenience, add a `into_flattened_vec(self) -> Vec<T>` to the `impl JsonArray`, so we can keep the convenient API, while not breaking the actual data.

In any case, if this is or isn't the solution, we need a stable way to collect represent the actual RPC response when it _is_ a nested `Vec`.

Thoughts? @liam0215 @LazaroHurtado

**Comment by LazaroHurtado** [comment]
This is an extremely good point as other RPC endpoints could return a JSON array of different dimensions and preserving the original form as much as possible would benefit the SDK user the most.

It would be a smart idea to always return a `Vec<Vec<T>>` and then depending on the command flatten the array but we could also take another route. We could keep the original code and alter it just a bit so that the passed generic is an array of a response struct (an example would be `JsonArray<Vec<InvalidBlock>>` or `JsonArray<Vec<Vec<Unistring>>>`). With this, we would no longer need a for-loop since `serde_json` would convert the `str_to_parse` to the generic type.

Here is a PoC that worked for our current commands after some small tweaks:
![Screen Shot 2021-05-11 at 7 18 13 PM](https://user-images.githubusercontent.com/54856229/117896075-c2025e00-b28d-11eb-815b-20611282a97a.png)


What do you guys think?

**Comment by liam0215** [comment]
Handling it with generics is really clean, but I think `JsonArray` should always represent the outermost array, so a 2d array of `Unistring`s could just be `JsonArray<Vec<Unistring>>` .

**Comment by LazaroHurtado** [comment]
Having `JsonArray` always represent a `Vec<T>` is a much better idea than what I suggested since there will always be a minimum of one array. Good idea Liam!

**Comment by astherath** [comment]
> Handling it with generics is really clean, but I think `JsonArray` should always represent the outermost array, so a 2d array of `Unistring`s could just be `JsonArray<Vec<Unistring>>` .

As of now, we `JsonArray` _has_ an internal `Vec<T>`, so I don't see how this would be different than the current implementation. Are you proposing that we have a private internal field in `JsonArray` that is `Vec<Vec<T>>`, and we just treat `JsonArray` as the interface wrapper over the first array?



> Here is a PoC that worked for our current commands after some small tweaks:
> ![Screen Shot 2021-05-11 at 7 18 13 PM](https://user-images.githubusercontent.com/54856229/117896075-c2025e00-b28d-11eb-815b-20611282a97a.png)
> 
> What do you guys think?

I think this is a really awesome idea and is similar to what I had in mind for the refactor. We wouldn't even be moving the trait contracts since we still only require `DeserializeOwned`. The only thing I don't like about this approach is that the `Response` struct is no longer the _only_ struct responsible for data representation, e.g.:
```rust
struct BlockIds {
    block_ids: JsonArray<String>,
}
```
would be something like:
```rust
struct BlockIds {
    nested_block_ids: JsonArray<InnerBlockIdVec>,
}

struct InnerBlockIdVec {
    block_ids: Vec<Vec<String>>,
}
```

I'm not agains this change per-say (in fact I think it's the only way of getting true data representation) but it should be considered as a cost.

**Comment by liam0215** [comment]
> 
> ```rust
> struct BlockIds {
>     block_ids: JsonArray<String>,
> }
> ```
> 
> would be something like:
> 
> ```rust
> struct BlockIds {
>     nested_block_ids: JsonArray<InnerBlockIdVec>,
> }
> 
> struct InnerBlockIdVec {
>     block_ids: Vec<Vec<String>>,
> }
> ```
> 
> I'm not agains this change per-say (in fact I think it's the only way of getting true data representation) but it should be considered as a cost.

I don't quite understand why we cant represent that as 
```rust
struct BlockIds {
    nested_block_ids: JsonArray<Vec<Unistring>>,
}
```
Since JsonArray holds the outer Vec.  Or maybe even
```rust
struct BlockIds {
    nested_block_ids: JsonArray<JsonArray<Unistring>>,
}
```

**Comment by astherath** [comment]
I like the
```rust
struct BlockIds {
    nested_block_ids: JsonArray<JsonArray<Unistring>>,
}
```
solution a lot actually, it makes it obvious that it's not a `Vec` and has some nice trait bounds. implementing now on upcoming pr.
